
def importMap():
    return{
        "Label 41: Right-Cerebral-White-Matter": ("Materia blanca", "Subcortical", "Derecho"),
        "Label 2: Left-Cerebral-White-Matter": ("Materia blanca", "Subcortical", "Izquierdo"),

        "Label 1028: ctx-lh-superiorfrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2028: ctx-rh-superiorfrontal": ("Frontal", "Corteza", "Derecho"),
        "Label 1027: ctx-lh-rostralmiddlefrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2027: ctx-rh-rostralmiddlefrontal": ("Frontal", "Corteza", "Derecho"),
        "Label 1003: ctx-lh-caudalmiddlefrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2003: ctx-rh-caudalmiddlefrontal": ("Frontal", "Corteza", "Derecho"),

        "Label 1031: ctx-lh-supramarginal": ("Parietal", "Corteza", "Izquierdo"),
        "Label 2031: ctx-rh-supramarginal": ("Parietal", "Corteza", "Derecho"),
        "Label 1025: ctx-lh-precuneus": ("Parietal", "Corteza", "Izquierdo"),
        "Label 2025: ctx-rh-precuneus": ("Parietal", "Corteza", "Derecho"),
        "Label 2029: ctx-rh-superiorparietal": ("Parietal", "Corteza", "Derecho"),
        "Label 1029: ctx-lh-superiorparietal": ("Parietal", "Corteza", "Izquierdo"),
        "Label 1008: ctx-lh-inferiorparietal": ("Parietal", "Corteza", "Izquierdo"),
        "Label 2008: ctx-rh-inferiorparietal": ("Parietal", "Corteza", "Derecho"),

        "Label 1018: ctx-lh-parsopercularis": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2018: ctx-rh-parsopercularis": ("Frontal", "Corteza", "Derecho"),
        "Label 1020: ctx-lh-parstriangularis": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2020: ctx-rh-parstriangularis": ("Frontal", "Corteza", "Derecho"),
        "Label 1019: ctx-lh-parsorbitalis": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2019: ctx-rh-parsorbitalis": ("Frontal", "Corteza", "Derecho"),
        "Label 1024: ctx-lh-precentral": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2024: ctx-rh-precentral": ("Frontal", "Corteza", "Derecho"),
        "Label 1017: ctx-lh-paracentral": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2017: ctx-rh-paracentral": ("Frontal", "Corteza", "Derecho"),

        "Label 2030: ctx-rh-superiortemporal": ("Temporal", "Corteza", "Derecho"),
        "Label 1030: ctx-lh-superiortemporal": ("Temporal", "Corteza", "Izquierdo"),
        "Label 2015: ctx-rh-middletemporal": ("Temporal", "Corteza", "Derecho"),
        "Label 1015: ctx-lh-middletemporal": ("Temporal", "Corteza", "Izquierdo"),
        "Label 2009: ctx-rh-inferiortemporal": ("Temporal", "Corteza", "Derecho"),
        "Label 1009: ctx-lh-inferiortemporal": ("Temporal", "Corteza", "Izquierdo"),
        "Label 2034: ctx-rh-transversetemporal": ("Temporal", "Corteza", "Derecho"),

        "Label 2011: ctx-rh-lateraloccipital": ("Occipital", "Corteza", "Derecho"),
        "Label 1011: ctx-lh-lateraloccipital": ("Occipital", "Corteza", "Izquierdo"),
        "Label 2005: ctx-rh-cuneus": ("Occipital", "Corteza", "Derecho"),
        "Label 1005: ctx-lh-cuneus": ("Occipital", "Corteza", "Izquierdo"),
        "Label 2021: ctx-rh-pericalcarine": ("Occipital", "Corteza", "Derecho"),

        "Label 1035: ctx-lh-insula": ("Insular", "Corteza", "Izquierdo"),
        "Label 2035: ctx-rh-insula": ("Insular", "Corteza", "Derecho"),

        "Label 53: Right-Hippocampus": ("Límbico", "Subcortical", "Derecho"),
        "Label 17: Left-Hippocampus": ("Límbico", "Subcortical", "Izquierdo"),

        "Label 18: Left-Amygdala": ("Límbico", "Subcortical", "Izquierdo"),

        "Label 1010: ctx-lh-isthmuscingulate": ("Límbico", "Corteza", "Izquierdo"),
        "Label 2010: ctx-rh-isthmuscingulate": ("Límbico", "Corteza", "Derecho"),
        "Label 1023: ctx-lh-posteriorcingulate": ("Límbico", "Corteza", "Izquierdo"),
        "Label 2023: ctx-rh-posteriorcingulate": ("Límbico", "Corteza", "Derecho"),
        "Label 1002: ctx-lh-caudalanteriorcingulate": ("Límbico", "Corteza", "Izquierdo"),
        "Label 2002: ctx-rh-caudalanteriorcingulate": ("Límbico", "Corteza", "Derecho"),
        "Label 1026: ctx-lh-rostralanteriorcingulate": ("Límbico", "Corteza", "Izquierdo"),
        "Label 2026: ctx-rh-rostralanteriorcingulate": ("Límbico", "Corteza", "Derecho"),

        "Label 1014: ctx-lh-medialorbitofrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2014: ctx-rh-medialorbitofrontal": ("Frontal", "Corteza", "Derecho"),
        "Label 1012: ctx-lh-lateralorbitofrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 2012: ctx-rh-lateralorbitofrontal": ("Frontal", "Corteza", "Derecho"),

        "Label 1006: ctx-lh-entorhinal": ("Límbico", "Corteza", "Izquierdo"),
        "Label 2006: ctx-rh-entorhinal": ("Límbico", "Corteza", "Derecho"),
        "Label 2016: ctx-rh-parahippocampal": ("Límbico", "Corteza", "Derecho"),

        "Label 77: WM-hypointensities": ("Materia blanca", "Hipointensidades", "Ambos"),

        "Label 12: Left-Putamen": ("Subcortical", "Subcortical", "Izquierdo"),
        "Label 43: Right-Lateral-Ventricle": ("Ventricular", "Líquido cefalorraquídeo", "Derecho"),
        "Label 44: Right-Inf-Lat-Vent": ("Ventricular", "Líquido cefalorraquídeo", "Derecho"),
        "Label 5: Left-Inf-Lat-Vent": ("Ventricular", "Líquido cefalorraquídeo", "Izquierdo"),

        "Label 63: Right-choroid-plexus": ("Ventricular", "Plexo coroideo", "Derecho"),
        "Label 60: Right-VentralDC": ("Subcortical", "Subcortical", "Derecho"),
        "Label 49: Right-Thalamus": ("Subcortical", "Subcortical", "Derecho"),
        "Label 50: Right-Caudate": ("Subcortical", "Subcortical", "Derecho"),

        "Label 47: Right-Cerebellum-Cortex": ("Cerebeloso", "Corteza", "Derecho"),
        "Label 8: Left-Cerebellum-Cortex": ("Cerebeloso", "Corteza", "Izquierdo"),
        "Label 50: Right-Caudate": ("Subcortical", "Núcleo de la base", "Derecho"),
        "Label 51: Right-Putamen": ("Subcortical", "Núcleo de la base", "Derecho"),
        "Label 52: Right-Pallidum": ("Subcortical", "Núcleo de la base", "Derecho"),
        "Label 53: Right-Hippocampus": ("Temporal", "Hipocampo", "Derecho"),
        "Label 54: Right-Amygdala": ("Temporal", "Amígdala", "Derecho"),
        "Label 58: Right-Accumbens-area": ("Subcortical", "Área Accumbens", "Derecho"),

        "Label 1002: ctx-lh-caudalanteriorcingulate": ("Límbico", "Corteza", "Izquierdo"),
        "Label 1007: ctx-lh-fusiform": ("Temporal", "Corteza", "Izquierdo"),
        "Label 1011: ctx-lh-lateraloccipital": ("Occipital", "Corteza", "Izquierdo"),
        "Label 1022: ctx-lh-postcentral": ("Parietal", "Corteza", "Izquierdo"),
        "Label 1024: ctx-lh-precentral": ("Frontal", "Corteza", "Izquierdo"),
        "Label 1025: ctx-lh-precuneus": ("Parietal", "Corteza", "Izquierdo"),
        "Label 1027: ctx-lh-rostralanteriorcingulate": ("Límbico", "Corteza", "Izquierdo"),
        "Label 1028: ctx-lh-rostralmiddlefrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 1029: ctx-lh-superiorfrontal": ("Frontal", "Corteza", "Izquierdo"),
        "Label 1031: ctx-lh-superiorparietal": ("Parietal", "Corteza", "Izquierdo"),
        "Label 1035: ctx-lh-transversetemporal": ("Temporal", "Corteza", "Izquierdo"),

        "Label 2002: ctx-rh-caudalanteriorcingulate": ("Límbico", "Corteza", "Derecho"),
        "Label 2007: ctx-rh-fusiform": ("Temporal", "Corteza", "Derecho"),
        "Label 2011: ctx-rh-lateraloccipital": ("Occipital", "Corteza", "Derecho"),
        "Label 2022: ctx-rh-postcentral": ("Parietal", "Corteza", "Derecho"),
        "Label 2024: ctx-rh-precentral": ("Frontal", "Corteza", "Derecho"),
        "Label 2025: ctx-rh-precuneus": ("Parietal", "Corteza", "Derecho"),
        "Label 2027: ctx-rh-rostralanteriorcingulate": ("Límbico", "Corteza", "Derecho"),
        "Label 2028: ctx-rh-rostralmiddlefrontal": ("Frontal", "Corteza", "Derecho"),
        "Label 2029: ctx-rh-superiorfrontal": ("Frontal", "Corteza", "Derecho"),
        "Label 2031: ctx-rh-superiorparietal": ("Parietal", "Corteza", "Derecho"),
        "Label 2035: ctx-rh-transversetemporal": ("Temporal", "Corteza", "Derecho"),

        "Label 251: CC_Posterior": ("Comisural", "Cuerpo calloso", "Ambos"),
        "Label 255: CC_Anterior": ("Comisural", "Cuerpo calloso", "Ambos"),
        "Label 2013: ctx-rh-lingual": ("Occipital", "Corteza", "Derecho"),
        "Label 4: Left-Lateral-Ventricle": ("Ventricular", "Líquido cefalorraquídeo", "Izquierdo"),
        "Label 7: Left-Cerebellum-White-Matter": ("Cerebeloso", "Materia blanca", "Izquierdo"),
        "Label 10: Left-Thalamus": ("Subcortical", "Núcleo de la base", "Izquierdo"),
        "Label 11: Left-Caudate": ("Subcortical", "Núcleo de la base", "Izquierdo"),
        "Label 13: Left-Pallidum": ("Subcortical", "Núcleo de la base", "Izquierdo"),
        "Label 0: Unknown": ("Desconocido", "Desconocido", "N/A"),
    }
